config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'products#index'

  resources :tasks

  controller :products do
    resources :products, only: %i[index show update]
    namespace :admin do
      resources :products
    end
  end

  resources :carts, only: %i[update delete]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_one_attached :thumbnail_image
  has_one_attached :main_image

  paginates_per 8

  validates :name, presence: true, length: { maximum: 255 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :stock, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :thumbnail_image, product_image: true
  validates :main_image, product_image: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  class ProductsController < ApplicationController
    http_basic_authenticate_with name: 'admin', password: 'pw'
    before_action :product_params, only: [:create]

    def index
      @products = Product.all.page(params[:page])
    end

    def show
      @product = Product.find(params[:id])
      @latest_products = Product.all.where(['id != ?', @product.id]).order(:created_at).limit(4)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        flash[:success] = "#{@product.name}を商品リストに登録しました。"
        redirect_to admin_products_url
      else
        render 'new', status: :unprocessable_entity
      end
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])
      if @product.update(product_params)
        flash[:success] = "#{@product.name}を更新しました。"
        redirect_to admin_products_url
      else
        render 'edit', status: :unprocessable_entity
      end
    end

    def destroy
      product = Product.find(params[:id])
      product.destroy
      flash[:success] = "#{product.name}を商品リストから削除しました。"
      redirect_to admin_product_url
    end

    private

    def product_params
      params.require(:product).permit(:name, :price, :description, :stock, :main_image, :thumbnail_image)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ActiveStorage::SetCurrent

  before_action :set_cart

  def set_cart
    if session[:cart].nil?
      @current_cart = Cart.new
      session[:cart] = @current_cart.serialize
    end
    if @current_cart.nil?
      @current_cart = Cart.deserialize(session[:cart])
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  
  #カートに追加などはここでやる
  def update
    if @current_cart.nil?
      redirect_to products_url
    end
    product = Product.find(params[:id])
    @current_cart.add(product)
    session[:cart] = @current_cart.serialize
    test = render turbo_stream: turbo_stream.replace(
      "cart-total", partial: "shared/cart_total", locals: { cart: @current_cart }
    )
    debugger
  end

  def delete
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page])
  end

  def show
    @product = Product.find(params[:id])
    @latest_products = Product.all.where(['id != ?', @product.id]).order(:created_at).limit(4)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :description, :status)
  end
end

app/helpers/application_form_builder.rb
# frozen_string_literal: true

class ApplicationFormBuilder < ActionView::Helpers::FormBuilder
  def hidden_field(_attribute, _options = {})
    raise 'Happiness chainではhidden_fieldの使用を禁止しています'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def hidden_field_tag(_name, _value = nil, _options = {})
    raise 'Happiness chainではhidden_field_tagの使用を禁止しています'
  end
end

app/helpers/product_helper.rb
# frozen_string_literal: true

module ProductHelper
  def url_include?(path)
    request.url.include? path
  end

  def admin_page?
    url_include?('/admin')
  end

  def get_product_detail_path(product)
    admin_page? ? admin_product_path(product) : product_path(product)
  end

  def get_product_form_path(product)
    if admin_page? && url_include?('new')
      admin_products_path
    elsif admin_page? && url_include?('edit')
      admin_product_path(product)
    end
  end

  def error?(product, name)
    product.errors.include?(name)
  end

  def set_invalid(product, name)
    error?(product, name) ? 'invalid' : ''
  end
end

app/views/admin/products/_admin_header.html.erb
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder"><%= locals[:title] %></h1>
      <p class="lead fw-normal text-white-50 mb-0">管理者のみ有効なページです</p>
    </div>
  </div>
</header>

app/views/admin/products/_product_form.html.erb
<div class="card product-form-card">
  <div class="card-body">
    <%= form_with model: locals[:product], url: get_product_form_path(locals[:product]), local: true do |form| %>
      <div class="row mb-3">
        <%= form.label :name, "商品名", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :name, class: "form-control #{set_invalid(locals[:product], "name")}" %>
          <% if error?(locals[:product], "name") %>
            <p class="red"><%= locals[:product].errors.full_messages_for(:name).first %></p>
          <% end %>
        </div>
      </div>
      <div class="row mb-3">
        <%= form.label :price, "商品価格", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :price, class: "form-control num-filed #{set_invalid(locals[:product], "price")}" %>
          <% if error?(locals[:product], "price") %>
            <p class="red"><%= locals[:product].errors.full_messages_for(:price).first %></p>
          <% end %>
        </div>
      </div>
      <div class="row mb-3">
        <%= form.label :description, "商品説明", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :description, class: "form-control #{set_invalid(locals[:product], "description")}" %>
          <% if error?(locals[:product], "description") %>
            <p class="red"><%= locals[:product].errors.full_messages_for(:description).first %></p>
          <% end %>
        </div>
      </div>
      <div class="row mb-3">
        <%= form.label :stock, "商品在庫", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= form.text_field :stock, class: "form-control num-filed #{set_invalid(locals[:product], "stock")}" %>
          <% if error?(locals[:product], "stock") %>
            <p class="red"><%= locals[:product].errors.full_messages_for(:stock).first %></p>
          <% end %>
        </div>
      </div>
      <div class="row mb-3">
        <%= form.label :main_image, "メイン画像", class: "col-sm-2 col-form-label #{set_invalid(locals[:product], "main_image")}" %>
        <div class="col-sm-10">
          <%= form.file_field :main_image, class: "form-control" %>
          <% if error?(locals[:product], "main_image") %>
            <p class="red"><%= locals[:product].errors.full_messages_for(:main_image).first %></p>
          <% end %>
        </div>
      </div>
      <div class="row mb-3">
        <%= form.label :thumbnail_image, "サムネ画像", class: "col-sm-2 col-form-label #{set_invalid(locals[:product], "thumbnail_image")}" %>
        <div class="col-sm-10">
          <%= form.file_field :thumbnail_image, class: "form-control" %>
          <% if error?(locals[:product], "thumbnail_image") %>
            <p class="red"><%= locals[:product].errors.full_messages_for(:thumbnail_image).first %></p>
          <% end %>
        </div>
      </div>
      <div class="right">
        <%= form.submit "登録", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/edit.html.erb
<!-- Header -->
<%= render 'admin_header', locals: { title: "商品編集ページ" } %>
<!-- From -->
<%= render 'product_form' , locals: {product: @product} %>

app/views/admin/products/index.html.erb
<!-- Header-->
<%= render 'admin_header', locals: { title: "商品一覧管理ページ" } %>
<!-- Section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @products.each do |product| %>
        <%= render "shared/product_card", locals: {product: product} %>
      <% end %>
    </div>
  </div>
</section>
<%= paginate @products %>
<!-- Footer-->
<%= render "shared/footer" %>

app/views/admin/products/new.html.erb
<!-- Header -->
<%= render 'admin_header', locals: { title: "商品作成ページ" } %>
<!-- From -->
<%= render 'product_form', locals: { product: @product } %>

app/views/admin/products/show.html.erb
<!-- Header -->
<%= render 'admin_header', locals: { title: "商品詳細ページ" } %>
<!-- Product section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-6"><%= image_tag @product.main_image.url, class: "card-img-top mb-5 mb-md-0" %></div>
      <div class="col-md-6">
        <h1 class="display-5 fw-bolder"><%= @product.name %></h1>
        <div class="fs-5 mb-5">
          <span><%= @product.price %></span>
        </div>
        <p class="lead"><%= @product.description %></p>
        <div class="d-flex">
          <input class="form-control text-center me-3" id="inputQuantity" type="num" value="<%= @product.stock %>" style="max-width: 3rem" />
          <button class="btn btn-outline-dark flex-shrink-0" type="button">
            <i class="bi-cart-fill me-1"></i>
            Add to cart
          </button>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Related items section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @latest_products.each do |product| %>
        <%= render "shared/product_card", locals: {product: product} %>
      <% end %>
    </div>
  </div>
</section>
<!-- Footer-->
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<!-- Navigation-->
<%= render "shared/navigation" %>
<!-- Header-->
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Shop in style</h1>
      <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
    </div>
  </div>
</header>
<!-- Section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @products.each do |product| %>
        <%= render "shared/product_card", locals: {product: product} %>
      <% end %>
    </div>
  </div>
</section>
<%= paginate @products %>
<!-- Footer-->
<%= render "shared/footer" %>

app/views/products/show.html.erb
<!-- Navigation-->
<%= render "shared/navigation" %>
<!-- Product section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="row gx-4 gx-lg-5 align-items-center">
      <div class="col-md-6"><%= image_tag @product.main_image.url, class: "card-img-top mb-5 mb-md-0" %></div>
      <div class="col-md-6">
        <h1 class="display-5 fw-bolder"><%= @product.name %></h1>
        <div class="fs-5 mb-5">
          <span><%= @product.price %></span>
        </div>
        <p class="lead"><%= @product.description %></p>
        <div class="d-flex">
          <input class="form-control text-center me-3" id="inputQuantity" type="num" value="<%= @product.stock %>" style="max-width: 3rem" />
          <button class="btn btn-outline-dark flex-shrink-0" type="button">
            <i class="bi-cart-fill me-1"></i>
            Add to cart
          </button>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Related items section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @latest_products.each do |product| %>
        <%= render "shared/product_card", locals: {product: product} %>
      <% end %>
    </div>
  </div>
</section>
<!-- Footer-->
<%= render "shared/footer" %>

app/views/shared/_cart_total.html.erb
<%= turbo_frame_tag "cart-total" do %>
  <div class="d-flex">
    <button class="btn btn-outline-dark" type="button">
      <i class="bi-cart-fill me-1"></i>
      カート
      <span class="badge bg-dark text-white ms-1 rounded-pill">
        <%= @current_cart.total %>
      </span>
    </button>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="#!">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#!">All Products</a></li>
            <li><hr class="dropdown-divider" /></li>
            <li><a class="dropdown-item" href="#!">Popular Items</a></li>
            <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
          </ul>
        </li>
      </ul>
      <%= render 'shared/cart_total', locals: { cart: @current_cart } %>
    </div>
  </div>
</nav>

app/views/shared/_product_card.html.erb
<div class="col mb-5">
  <div class="card">
    <%= link_to  get_product_detail_path(locals[:product]), class: "product-card-link" do %>
      <!-- Product image-->
      <%= image_tag locals[:product].thumbnail_image.url, class: "product-card-img" %>
      <!-- Product details-->
      <div class="card-body p-4">
        <div class="text-center">
          <!-- Product name-->
          <h5 class="fw-bolder"><%= locals[:product].name %></h5>
          <!-- Product price-->
          <%= locals[:product].price %>
        </div>
      </div>
      <!-- Product actions-->
      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
        <% if admin_page? %>
          <div class=" container">
            <div class="row">
              <div class="col text-center">
                <%= link_to "編集", edit_admin_product_path(locals[:product]) , class: "btn btn-outline-dark mt-auto" %>
              </div>
              <div class="col text-center">
                <%= link_to "削除", admin_product_path(locals[:product]), data: { turbo_method: :delete, turbo_confirm: "商品#{locals[:product].name}を本当に削除しますか？" }, class: "btn btn-outline-dark mt-auto" %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="text-center">
            <%= link_to "カートに追加", cart_path(locals[:product]), data: { turbo_method: :patch }, class: "btn btn-outline-dark mt-auto" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.number_field :status %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>
  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>
<%= render "form", task: @task %>
<br>
<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Tasks</h1>
<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>
<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render "form", task: @task %>
<br>
<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @task %>
<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>
  <%= button_to "Destroy this task", @task, method: :delete %>
</div>